In [ ]:
import pandas as pd

file_path = "/Users/alex/SPS_MS_DS/DATA_602/Data_602_FINAL_PROJECT/Obesity_Risk_Factors_CDC.csv"
df = pd.read_csv(file_path)

summary = {
    "Shape": df.shape,
    "Data Types": df.dtypes.value_counts().to_dict(),
    "Missing Values": df.isnull().sum().sort_values(ascending=False).head(10),
    "Sample Data": df.head(5)
}

summary

{'Shape': (104272, 33),
 'Data Types': {dtype('O'): 24, dtype('float64'): 6, dtype('int64'): 3},
 'Missing Values': Total                         100548
 Sex                            96824
 Data_Value_Footnote            93505
 Data_Value_Footnote_Symbol     93505
 Education                      89376
 Age(years)                     81928
 Income                         78204
 Race/Ethnicity                 74480
 Data_Value_Unit                15400
 Low_Confidence_Limit           10767
 dtype: int64,
 'Sample Data':    YearStart  YearEnd LocationAbbr LocationDesc Datasource  \
 0       2011     2011           AK       Alaska      BRFSS
 1       2011     2011           AK       Alaska      BRFSS
 2       2011     2011           AK       Alaska      BRFSS
 3       2011     2011           AK       Alaska      BRFSS
 4       2011     2011           AK       Alaska      BRFSS

                      Class                         Topic  \
 0  Obesity / Weight Status       Obesity / Weight Status
 1  Obesity / Weight Status       Obesity / Weight Status
 2        Physical Activity  Physical Activity - Behavior
 3  Obesity / Weight Status       Obesity / Weight Status
 4  Obesity / Weight Status       Obesity / Weight Status

                                             Question  Data_Value_Unit  \
 0  Percent of adults aged 18 years and older who ...           2011.0
 1  Percent of adults aged 18 years and older who ...           2011.0
 2  Percent of adults who achieve at least 150 min...           2011.0
 3  Percent of adults aged 18 years and older who ...           2011.0
 4  Percent of adults aged 18 years and older who ...           2011.0

   Data_Value_Type  ...                        GeoLocation  ClassID TopicID  \
 0           Value  ...  (64.845079957001, -147.722059036)      OWS    OWS1
 1           Value  ...  (64.845079957001, -147.722059036)      OWS    OWS1
 2           Value  ...  (64.845079957001, -147.722059036)       PA     PA1
 3           Value  ...  (64.845079957001, -147.722059036)      OWS    OWS1
 4           Value  ...  (64.845079957001, -147.722059036)      OWS    OWS1

   QuestionID  DataValueTypeID  LocationID  StratificationCategory1  \
 0       Q036            VALUE           2           Race/Ethnicity
 1       Q036            VALUE           2           Race/Ethnicity
 2       Q044            VALUE           2                      Sex
 3       Q036            VALUE           2              Age (years)
 4       Q037            VALUE           2                   Income

      Stratification1 StratificationCategoryId1 StratificationID1
 0    2 or more races                      RACE         RACE2PLUS
 1              Other                      RACE           RACEOTH
 2             Female                       SEX            FEMALE
 3            35 - 44                     AGEYR         AGEYR3544
 4  $15,000 - $24,999                       INC           INC1525

 [5 rows x 33 columns]}

In [7]:
df.head(5)

,YearStart,YearEnd,LocationAbbr,LocationDesc,Datasource,Class,Topic,Question,Data_Value_Unit,Data_Value_Type,...,GeoLocation,ClassID,TopicID,QuestionID,DataValueTypeID,LocationID,StratificationCategory1,Stratification1,StratificationCategoryId1,StratificationID1
0,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q036,VALUE,2,Race/Ethnicity,2 or more races,RACE,RACE2PLUS
1,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q036,VALUE,2,Race/Ethnicity,Other,RACE,RACEOTH
2,2011,2011,AK,Alaska,BRFSS,Physical Activity,Physical Activity - Behavior,Percent of adults who achieve at least 150 min...,2011.0,Value,...,"(64.845079957001, -147.722059036)",PA,PA1,Q044,VALUE,2,Sex,Female,SEX,FEMALE
3,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q036,VALUE,2,Age (years),35 - 44,AGEYR,AGEYR3544
4,2011,2011,AK,Alaska,BRFSS,Obesity / Weight Status,Obesity / Weight Status,Percent of adults aged 18 years and older who ...,2011.0,Value,...,"(64.845079957001, -147.722059036)",OWS,OWS1,Q037,VALUE,2,Income,"$15,000 - $24,999",INC,INC1525